[package]
name = "firmware"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.avr-device]
version = "0.3.1"
features = ["atmega328p"]
